### ISSUE TITLE
Not working under debian jessie

### ISSUE THREAD

**Issue by pRiVi** [pRiVi/git-dit#1]
root@journaldev:/opt/git-dit# git dit new
git: 'interpret-trailers' ist kein Git-Kommando. Siehe 'git --help'.
/opt/git-dit/git-dit-new: Zeile 123: /opt/git-dit/.git/COMMIT_EDITMSG: Permission denied
The format of the provided message is faulty
root@journaldev:/opt/git-dit#

**Comment by neithernut** [comment]
Strange. What version of git are you using?

**Comment by pRiVi** [comment]
The default on debian jessie, there is no "git interpret-trailers":

root@journaldev:/opt/git-dit# git --version
git version 2.1.4
root@journaldev:/opt/git-dit#

**Comment by neithernut** [comment]
Huh. Ok. I'm running 2.11 here. 2.1 isn't even in my package repo any more. @matthiasbeyer will most likely also run a more recent version.

We have to investigate in which version `interpret-trailers` was introduced. We will then either depend on at least that version or add our own script (maybe we can simply reuse git-dit-extract-trailers).

Also: could it be that your `EDITOR` variable is not set? If so, we probably run into errors here because we forgot to set it from the git-config if it isn't set already.

**Comment by pRiVi** [comment]
I donnot have an EDITOR... For what is it needed?

root@journaldev:/opt/git-dit# echo $EDITOR

root@journaldev:/opt/git-dit# git interpret-trailers
git: 'interpret-trailers' ist kein Git-Kommando. Siehe 'git --help'.
root@journaldev:/opt/git-dit#

**Comment by pRiVi** [comment]
If I set there comes an editor, but if I save:

root@journaldev:/opt/git-dit# git dit new
git: 'interpret-trailers' ist kein Git-Kommando. Siehe 'git --help'.
[dit][new]: 832de908d68d8f0a66ae4da2445a8f6522e211ff
root@journaldev:/opt/git-dit# git dit list
832de908d68d8f0a66ae4da2445a8f6522e211ff (vor 45 Sekunden) Test
root@journaldev:/opt/git-dit# 

... Seems to work?

**Comment by pRiVi** [comment]
Another error?

root@journaldev:/opt/git-dit# git dit push origin
error: unknown option `contains'
Verwendung: git for-each-ref [Optionen] [<Muster>]

    -s, --shell           formatiert Platzhalter als Shell-String
    -p, --perl            formatiert Platzhalter als Perl-String
    --python              formatiert Platzhalter als Python-String
    --tcl                 formatiert Platzhalter als TCL-String

    --count <Anzahl>      zeigt nur <n> passende Referenzen
    --format <Format>     für die Ausgabe zu verwendendes Format
    --sort <Schüssel>     sortiere nach diesem Feld

Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Everything up-to-date
root@journaldev:/opt/git-dit#

**Comment by neithernut** [comment]
`git-interpret-trailers` apparently was introduced in `git-2.2`.

----

The `EDITOR` variable is used for spawning an editor.

----

> If I set there comes an editor, but if I save:
> ... Seems to work?

Yep, seems to work.

----

> Another error?

Looks like another functionality which was introduced after `git-2.1`.

**Comment by pRiVi** [comment]
Why is "git push" not pushing the issues?

**Comment by matthiasbeyer** [comment]
> Why is "git push" not pushing the issues?

Because `git-push` only pushes branches, which live in another namespace than the references we create in the repository.
Also, it is a convenience thing: I, for one, do not want issues to be pushed whenever I `git-push`, but I want that to be an additional step.

**Comment by pRiVi** [comment]
This a very good thing!

Now we just must get it under debian jessie working. :-)

**Comment by pRiVi** [comment]
Sadly I cannot use it.

**Comment by pRiVi** [comment]
Moved to bug neithernut/git-dit#16
